-- ============================================================================
-- KIU GREENCARD SYSTEM - REGULATION WORKFLOW MIGRATION
-- This migration restructures the system to match official university regulations
-- 
-- WORKFLOW: Student → Admissions → Finance → Admissions → Student
-- ============================================================================

USE Greencard_system;

-- ============================================================================
-- STEP 1: BACKUP EXISTING DATA (Optional)
-- ============================================================================
-- Run this first if you have existing data:
-- CREATE TABLE payment_submissions_backup AS SELECT * FROM payment_submissions;
-- CREATE TABLE payment_verifications_backup AS SELECT * FROM payment_verifications;

-- ============================================================================
-- STEP 2: DROP OLD TABLES (Careful! This will delete data)
-- ============================================================================
DROP TABLE IF EXISTS green_cards;
DROP TABLE IF EXISTS document_uploads;
DROP TABLE IF EXISTS payment_verifications;
DROP TABLE IF EXISTS payment_submissions;

-- ============================================================================
-- STEP 3: CREATE NEW DOCUMENT_SUBMISSIONS TABLE
-- (Replaces payment_submissions - now handles academic documents)
-- ============================================================================

CREATE TABLE document_submissions (
    submission_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT UNSIGNED NOT NULL,
    
    -- Admission and Sponsorship
    admission_letter_path VARCHAR(500) NULL COMMENT 'Admission letter',
    is_bursary BOOLEAN DEFAULT FALSE COMMENT 'Whether student is bursary sponsored',
    bursary_award_letter_path VARCHAR(500) NULL COMMENT 'Bursary award letter (required when bursary)',

    -- Academic Documents (Required by regulation)
    s6_certificate_path VARCHAR(500) NULL COMMENT 'S.6 Certificate/Transcript',
    national_id_path VARCHAR(500) NULL COMMENT 'National ID copy',
    school_id_path VARCHAR(500) NULL COMMENT 'Former School ID copy',
    passport_photo_path VARCHAR(500) NULL COMMENT 'Passport-size photo',
    
    -- Student Information
    full_name VARCHAR(255) NOT NULL,
    date_of_birth DATE NOT NULL,
    program VARCHAR(255) NOT NULL,
    faculty VARCHAR(255) NOT NULL,
    intake_year YEAR NOT NULL,
    intake_semester ENUM('semester_1', 'semester_2', 'semester_3') NOT NULL,
    
    -- Payment Information (for finance verification)
    payment_reference VARCHAR(100) NULL COMMENT 'Bank reference number',
    payment_amount DECIMAL(10, 2) NULL COMMENT 'Amount paid',

    payment_currency ENUM('UGX','USD') NOT NULL DEFAULT 'UGX' COMMENT 'Currency of payment amount',
    payment_date DATE NULL COMMENT 'Date of payment',
    bank_slip_path VARCHAR(500) NULL COMMENT 'Bank slip proof',
    
    -- Registration Number (Generated by Admissions)
    registration_number VARCHAR(50) NULL UNIQUE COMMENT 'Auto-generated by admissions',
    
    -- Workflow Status
    status ENUM(
        'pending_admissions',           -- Step 1: Waiting for admissions review
        'under_admissions_review',      -- Step 2: Admissions reviewing documents
        'admissions_approved',          -- Step 3: Admissions approved, forwarded to finance
        'admissions_rejected',          -- Rejected by admissions
        'pending_finance',              -- Step 4: Waiting for finance payment confirmation
        'under_finance_review',         -- Step 5: Finance reviewing payment
        'finance_approved',             -- Step 6: Finance approved, back to admissions
        'finance_rejected',             -- Rejected by finance
        'pending_greencard',            -- Step 7: Waiting for green card generation
        'greencard_issued',             -- Step 8: Green card issued - COMPLETE
        'cancelled'                     -- Cancelled by student or admin
    ) NOT NULL DEFAULT 'pending_admissions',
    
    -- Tracking
    submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    -- Metadata
    priority_level ENUM('normal', 'urgent', 'very_urgent') DEFAULT 'normal',
    notes TEXT NULL COMMENT 'Internal notes',
    
    CONSTRAINT fk_doc_submission_user 
        FOREIGN KEY (user_id) REFERENCES users(user_id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    
    INDEX idx_user_submissions (user_id, submitted_at DESC),
    INDEX idx_status (status, submitted_at),
    INDEX idx_registration_number (registration_number)
) ENGINE=InnoDB COMMENT='Student document submissions following regulation workflow';

-- ============================================================================
-- STEP 4: CREATE ADMISSIONS_VERIFICATIONS TABLE
-- (New table - handles document verification by admissions office)
-- ============================================================================

CREATE TABLE admissions_verifications (
    verification_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    submission_id BIGINT UNSIGNED NOT NULL UNIQUE,
    verified_by_user_id BIGINT UNSIGNED NOT NULL COMMENT 'Admissions staff member',
    
    -- Document Verification
    s6_certificate_verified BOOLEAN DEFAULT FALSE,
    national_id_verified BOOLEAN DEFAULT FALSE,
    school_id_verified BOOLEAN DEFAULT FALSE,
    documents_authentic BOOLEAN DEFAULT FALSE,
    
    -- Decision
    is_approved BOOLEAN NOT NULL,
    rejection_reason TEXT NULL COMMENT 'Required if rejected',
    verification_notes TEXT NULL COMMENT 'Admissions officer notes',
    
    -- Registration Number Generation
    registration_number VARCHAR(50) NULL COMMENT 'Generated upon approval',
    registration_generated_at TIMESTAMP NULL,
    
    -- Forwarding to Finance
    forwarded_to_finance BOOLEAN DEFAULT FALSE,
    forwarded_at TIMESTAMP NULL,
    
    -- Timing
    verification_duration_seconds INT UNSIGNED NULL,
    verified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT fk_adm_verification_submission 
        FOREIGN KEY (submission_id) REFERENCES document_submissions(submission_id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    
    CONSTRAINT fk_adm_verification_user 
        FOREIGN KEY (verified_by_user_id) REFERENCES users(user_id)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    
    INDEX idx_verified_by (verified_by_user_id),
    INDEX idx_approved (is_approved, verified_at)
) ENGINE=InnoDB COMMENT='Admissions office document verification records';

-- ============================================================================
-- STEP 5: CREATE FINANCE_CLEARANCES TABLE
-- (Replaces payment_verifications - now handles payment clearance confirmation)
-- ============================================================================

CREATE TABLE finance_clearances (
    clearance_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    submission_id BIGINT UNSIGNED NOT NULL UNIQUE,
    verified_by_user_id BIGINT UNSIGNED NOT NULL COMMENT 'Finance officer',
    
    -- Payment Verification
    payment_reference VARCHAR(100) NULL,
    payment_amount_verified DECIMAL(10, 2) NOT NULL,
    payment_date_verified DATE NOT NULL,
    required_amount DECIMAL(10, 2) NOT NULL,
    percentage_paid DECIMAL(5, 2) GENERATED ALWAYS AS ((payment_amount_verified / required_amount) * 100) STORED,
    
    -- Finance System Integration
    finance_api_reference VARCHAR(255) NULL COMMENT 'External finance system reference',
    finance_api_response JSON NULL COMMENT 'API response for audit',
    
    -- Decision
    is_cleared BOOLEAN NOT NULL COMMENT 'TRUE = payment confirmed, FALSE = rejected',
    clearance_notes TEXT NULL COMMENT 'Finance officer notes',
    rejection_reason TEXT NULL COMMENT 'Required if not cleared',
    
    -- Manual Handling
    manual_override BOOLEAN DEFAULT FALSE,
    override_reason TEXT NULL,
    
    -- Forwarding Back to Admissions
    forwarded_to_admissions BOOLEAN DEFAULT FALSE,
    forwarded_at TIMESTAMP NULL,
    
    -- Timing
    verification_duration_seconds INT UNSIGNED NULL,
    verified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT fk_fin_clearance_submission 
        FOREIGN KEY (submission_id) REFERENCES document_submissions(submission_id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    
    CONSTRAINT fk_fin_clearance_user 
        FOREIGN KEY (verified_by_user_id) REFERENCES users(user_id)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    
    INDEX idx_verified_by (verified_by_user_id),
    INDEX idx_cleared (is_cleared, verified_at)
) ENGINE=InnoDB COMMENT='Finance department payment clearance records';

-- ============================================================================
-- STEP 6: RECREATE GREEN_CARDS TABLE (with updated references)
-- ============================================================================

CREATE TABLE green_cards (
    card_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    submission_id BIGINT UNSIGNED NOT NULL UNIQUE,
    user_id BIGINT UNSIGNED NOT NULL,
    
    -- Card Details
    registration_number VARCHAR(50) NOT NULL UNIQUE,
    card_number VARCHAR(50) NOT NULL UNIQUE COMMENT 'Green card unique number',
    qr_code_data TEXT NOT NULL COMMENT 'QR code content',
    qr_code_image_path VARCHAR(500) NULL COMMENT 'Generated QR code image',
    
    -- Student Information
    full_name VARCHAR(255) NOT NULL,
    program VARCHAR(255) NOT NULL,
    faculty VARCHAR(255) NOT NULL,
    student_photo_path VARCHAR(500) NOT NULL,
    
    -- Validity
    issue_date DATE NOT NULL,
    expiry_date DATE NOT NULL,
    academic_year VARCHAR(20) NOT NULL,
    semester ENUM('semester_1', 'semester_2', 'semester_3') NOT NULL,
    
    -- PDF Document
    pdf_path VARCHAR(500) NOT NULL COMMENT 'Generated green card PDF',
    digital_signature TEXT NULL COMMENT 'Digital signature for authenticity',
    
    -- Status
    is_active BOOLEAN DEFAULT TRUE,
    revoked_at TIMESTAMP NULL,
    revocation_reason TEXT NULL,
    
    -- Issuance Details
    issued_by_user_id BIGINT UNSIGNED NOT NULL COMMENT 'Admissions officer who issued',
    issued_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    downloaded_at TIMESTAMP NULL COMMENT 'First download timestamp',
    download_count INT UNSIGNED DEFAULT 0,
    
    -- Metadata
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    CONSTRAINT fk_greencard_submission 
        FOREIGN KEY (submission_id) REFERENCES document_submissions(submission_id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    
    CONSTRAINT fk_greencard_user 
        FOREIGN KEY (user_id) REFERENCES users(user_id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    
    CONSTRAINT fk_greencard_issued_by 
        FOREIGN KEY (issued_by_user_id) REFERENCES users(user_id)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    
    INDEX idx_registration_number (registration_number),
    INDEX idx_user_cards (user_id, issue_date DESC),
    INDEX idx_active_cards (is_active, issue_date)
) ENGINE=InnoDB COMMENT='Digital green cards issued to students';

-- ============================================================================
-- STEP 7: RECREATE DOCUMENT_UPLOADS TABLE (optional - for additional docs)
-- ============================================================================

CREATE TABLE document_uploads (
    upload_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    submission_id BIGINT UNSIGNED NOT NULL,
    document_type ENUM('s6_certificate', 'national_id', 'school_id', 'passport_photo', 'bank_slip', 'other') NOT NULL,
    file_path VARCHAR(500) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    file_size_bytes BIGINT UNSIGNED NOT NULL,
    mime_type VARCHAR(100) NOT NULL,
    is_encrypted BOOLEAN DEFAULT TRUE,
    uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT fk_doc_upload_submission 
        FOREIGN KEY (submission_id) REFERENCES document_submissions(submission_id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    
    INDEX idx_submission_docs (submission_id, document_type)
) ENGINE=InnoDB COMMENT='Additional document uploads linked to submissions';

-- ============================================================================
-- STEP 8: UPDATE NOTIFICATIONS TABLE (if needed)
-- ============================================================================
-- No changes needed - notifications table remains the same

-- ============================================================================
-- STEP 9: CREATE WORKFLOW_HISTORY TABLE (Track status changes)
-- ============================================================================

CREATE TABLE workflow_history (
    history_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    submission_id BIGINT UNSIGNED NOT NULL,
    from_status VARCHAR(50) NULL,
    to_status VARCHAR(50) NOT NULL,
    changed_by_user_id BIGINT UNSIGNED NULL,
    department ENUM('student', 'admissions', 'finance', 'system') NOT NULL,
    notes TEXT NULL,
    changed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT fk_workflow_submission 
        FOREIGN KEY (submission_id) REFERENCES document_submissions(submission_id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    
    CONSTRAINT fk_workflow_user 
        FOREIGN KEY (changed_by_user_id) REFERENCES users(user_id)
        ON DELETE SET NULL ON UPDATE CASCADE,
    
    INDEX idx_submission_history (submission_id, changed_at)
) ENGINE=InnoDB COMMENT='Complete audit trail of workflow status changes';

-- ============================================================================
-- STEP 10: ENABLE FOREIGN KEY CHECKS
-- ============================================================================
SET FOREIGN_KEY_CHECKS = 1;

-- ============================================================================
-- STEP 11: PHASE 2 WORKFLOW ENHANCEMENTS
-- Adds: resubmission flow, document/finance flags, partial/deferral support
-- ============================================================================

ALTER TABLE document_submissions
    MODIFY status ENUM(
        'pending_admissions',
        'under_admissions_review',
        'admissions_approved',
        'admissions_rejected',
        'resubmission_requested',
        'pending_finance',
        'under_finance_review',
        'finance_approved',
        'finance_rejected',
        'finance_pending',
        'pending_greencard',
        'greencard_issued',
        'cancelled'
    ) NOT NULL DEFAULT 'pending_admissions';

ALTER TABLE document_submissions
    ADD COLUMN IF NOT EXISTS resubmission_reason TEXT NULL,
    ADD COLUMN IF NOT EXISTS resubmission_requested_at TIMESTAMP NULL,
    ADD COLUMN IF NOT EXISTS resubmission_count INT UNSIGNED NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS admission_letter_path VARCHAR(500) NULL,
    ADD COLUMN IF NOT EXISTS is_bursary BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS bursary_award_letter_path VARCHAR(500) NULL,
    ADD COLUMN IF NOT EXISTS admissions_flag_status ENUM('none', 'incomplete', 'suspicious', 'mismatch') NOT NULL DEFAULT 'none',
    ADD COLUMN IF NOT EXISTS admissions_flag_notes TEXT NULL,
    ADD COLUMN IF NOT EXISTS finance_flag_status ENUM('none', 'partial_payment', 'deferral', 'pending_confirmation') NOT NULL DEFAULT 'none',
    ADD COLUMN IF NOT EXISTS finance_flag_notes TEXT NULL;

ALTER TABLE admissions_verifications
    ADD COLUMN IF NOT EXISTS requested_resubmission BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS flag_status ENUM('none', 'incomplete', 'suspicious', 'mismatch') NOT NULL DEFAULT 'none',
    ADD COLUMN IF NOT EXISTS flag_notes TEXT NULL;

ALTER TABLE finance_clearances
    ADD COLUMN IF NOT EXISTS is_pending BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS pending_reason TEXT NULL,
    ADD COLUMN IF NOT EXISTS partial_payment BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS deferral_approved BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS deferral_reason TEXT NULL;

ALTER TABLE student_profiles
    ADD COLUMN IF NOT EXISTS registration_number VARCHAR(50) NULL UNIQUE;

CREATE INDEX idx_document_flags ON document_submissions (admissions_flag_status, finance_flag_status, status);

-- ============================================================================
-- STEP 12: FINANCE POLICY TABLES (BURSARY + FX RATE)
-- ============================================================================

CREATE TABLE IF NOT EXISTS bursary_forward_list (
    bursary_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT UNSIGNED NULL,
    admission_number VARCHAR(50) NOT NULL,
    full_name VARCHAR(255) NOT NULL,
    program VARCHAR(255) NULL,
    intake_year YEAR NOT NULL,
    intake_semester ENUM('semester_1', 'semester_2', 'semester_3') NOT NULL,
    forwarded_by_user_id BIGINT UNSIGNED NULL,
    forwarded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    confirmation_status ENUM('pending', 'confirmed') NOT NULL DEFAULT 'confirmed',
    notes TEXT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_bursary_forward_user
        FOREIGN KEY (user_id) REFERENCES users(user_id)
        ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_bursary_forwarded_by
        FOREIGN KEY (forwarded_by_user_id) REFERENCES users(user_id)
        ON DELETE SET NULL ON UPDATE CASCADE,
    INDEX idx_bursary_lookup (admission_number, intake_year, intake_semester, is_active),
    INDEX idx_bursary_status (confirmation_status, forwarded_at)
) ENGINE=InnoDB COMMENT='Students forwarded by Bursary Department to Finance';

CREATE TABLE IF NOT EXISTS semester_exchange_rates (
    rate_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    intake_year YEAR NOT NULL,
    intake_semester ENUM('semester_1', 'semester_2', 'semester_3') NOT NULL,
    usd_to_ugx_rate DECIMAL(10, 4) NOT NULL,
    effective_from DATE NOT NULL,
    published_by_user_id BIGINT UNSIGNED NULL,
    published_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    notes TEXT NULL,
    CONSTRAINT fk_fx_rate_published_by
        FOREIGN KEY (published_by_user_id) REFERENCES users(user_id)
        ON DELETE SET NULL ON UPDATE CASCADE,
    UNIQUE KEY uq_fx_rate_semester (intake_year, intake_semester, effective_from),
    INDEX idx_fx_rate_active (intake_year, intake_semester, is_active)
) ENGINE=InnoDB COMMENT='Finance-published semester exchange rates for USD payments';

-- ============================================================================
-- MIGRATION COMPLETE
-- ============================================================================

-- Next Steps:
-- 1. Update application code to use new tables and workflow
-- 2. Update upload directories for new document types
-- 3. Modify student submission forms
-- 4. Create admissions verification module
-- 5. Update finance module for clearance confirmation
-- 6. Update admissions module for green card issuance

SELECT 'Database migration completed successfully!' AS status;
